
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-angular-pipeline-test-jenkins
    ports:
      - "8080:8080" # Map Jenkins default port
      - "50000:50000" # Map Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Required for Docker in Docker (optional, based on your needs)
    environment:
      JENKINS_OPTS: "--httpPort=8080"
    networks:
      - angular-pipeline-test-network
    restart: always

networks:
  angular-pipeline-test-network:
    external: true

volumes:
  jenkins_home:
    driver: local
